version: '3.7'
services:
  #
  # Client
  #
  client2:
    image: von-network-base2
    command: ./scripts/start_client.sh
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - RUST_LOG=${RUST_LOG}
    networks:
      - von
    volumes:
      - client-data2:/home/indy/.indy_client
      - ./tmp:/tmp

  #
  # Webserver
  #
  webserver2:
    image: von-network-base2
    command: bash -c 'sleep 10 && ./scripts/start_webserver.sh'
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
      - GENESIS_URL=${GENESIS_URL}
      - ANONYMOUS=${ANONYMOUS}
      - LEDGER_SEED=${LEDGER_SEED}
      - LEDGER_CACHE_PATH=${LEDGER_CACHE_PATH}
      - MAX_FETCH=${MAX_FETCH:-50000}
      - RESYNC_TIME=${RESYNC_TIME:-120}
      - REGISTER_NEW_DIDS=${REGISTER_NEW_DIDS:-True}
      - LEDGER_INSTANCE_NAME=${LEDGER_INSTANCE_NAME:-localhost}
      - WEB_ANALYTICS_SCRIPT=${WEB_ANALYTICS_SCRIPT}
      - INFO_SITE_TEXT=${INFO_SITE_TEXT}
      - INFO_SITE_URL=${INFO_SITE_URL}
    networks:
      - von
    ports:
      - ${WEB_SERVER_HOST_PORT:-7000}:8000
    volumes:
      - ./config:/home/indy/config
      - ./server:/home/indy/server
      - webserver-cli2:/home/indy/.indy-cli
      - webserver-ledger2:/home/indy/ledger

  #
  # Synchronization test
  #
  synctest2:
    image: von-network-base2
    command: ./scripts/start_synctest.sh
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    networks:
      - von
    ports:
      - ${WEB_SERVER_HOST_PORT:-7000}:8000
    volumes:
      - ./config:/home/indy/config
      - ./server:/home/indy/server
      - webserver-cli2:/home/indy/.indy-cli
      - webserver-ledger2:/home/indy/ledger

  #
  # Nodes
  #
  nodes2:
    image: von-network-base2
    command: ./scripts/start_nodes.sh
    networks:
      - von
    ports:
      - 7701:7701
      - 7702:7702
      - 7703:7703
      - 7704:7704
      - 7705:7705
      - 7706:7706
      - 7707:7707
      - 7708:7708
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - nodes-data2:/home/indy/ledger

  node12:
    image: von-network-base2
    command: ./scripts/start_node.sh 1
    networks:
      - von
    ports:
      - 7701:7701
      - 7702:7702
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node1-data2:/home/indy/ledger

  node22:
    image: von-network-base2
    command: ./scripts/start_node.sh 2
    networks:
      - von
    ports:
      - 7703:7703
      - 7704:7704
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node2-data2:/home/indy/ledger

  node32:
    image: von-network-base2
    command: ./scripts/start_node.sh 3
    networks:
      - von
    ports:
      - 7705:7705
      - 7706:7706
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node3-data2:/home/indy/ledger

  node42:
    image: von-network-base2
    command: ./scripts/start_node.sh 4
    networks:
      - von
    ports:
      - 7707:7707
      - 7708:7708
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node4-data2:/home/indy/ledger

networks:
  von:
    name: von2

volumes:
  client-data2:
    name: client-data2
  webserver-cli2:
    name: webserver-cli2
  webserver-ledger2:
    name: webserver-ledger2
  node1-data2:
    name: node1-data2
  node2-data2:
    name: node2-data2
  node3-data2:
    name: node3-data2
  node4-data2:
    name: node4-data2
  nodes-data2:
    name: nodes-data2
